#!/usr/bin/env bash
# Configures an Ubuntu server so that localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127\.0\.0\.1\s*localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i '/facebook.com/d' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts